### ISSUE TITLE
Issue with building RoPE - CUDA MISMATCH

### ISSUE THREAD

**Issue by gchhablani** [naver/croco#10]
Hi,
I am getting this error on trying to build RoPE:
```
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError: 
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.
```

Any help on how I can fix this?

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

You have most likely compile the CUDA kernel using a cuda version of 12.1 while your pytorch is built/installed with cuda 11.7.
You can check the cuda version you are using, you can run `nvcc -V`.
If this is it, you need either to upgrade your pytorch install with cuda 12.1 ; or to compile the kernels with a cuda version 11.7; note that you can set the path to cuda using `export CUDA_HOME=<path_to_cuda_11.7>` before compiling.

Best
Philippe
