### ISSUE TITLE
train croco-stereo with a dataset without disparity map

### ISSUE THREAD

**Issue by YuanjueMa** [naver/croco#11]
Hi, 
thanks for your work!
I'm trying to train the croco-stereo with my own dataset, but this network needs to provide a disparity map for training. Is it possible to train this network without a disparity map?

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

In our work we have only considered the supervised case.
I am not familiar enough with the self-supervised stereo community, but I imagine there are some self-supervised work based on eg reconstruction loss. This kind of work is usually totally independent from the network architecture and thus could straightforwardly be applied to CroCo-Stereo.
For optical flow, you can for instance refer to https://arxiv.org/abs/1608.05842 and for stereo to https://arxiv.org/abs/1709.00930.

Best
Philippe
