### ISSUE TITLE
[CNN architecture support]

### ISSUE THREAD

**Issue by CaptainEven** [naver/croco#12]
Out of curiosity, may i ask is there any possibility to make a version of CNN based CROCO self-supervised pipeline?

**Comment by xjcvip007** [comment]
Maybe 《MC-JEPA: A Joint-Embedding Predictive Architecture for Self-Supervised Learning of Motion and Content Features》can meet your requirements.

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

Masked Image Modeling (MIM) methods in general are well desiged for patch-based architectures such as ViTs.
There have been some attemps to extend MIM to CNNs, eg [Architecture-Agnostic Masked Image Modeling -- From ViT back to CNN](https://arxiv.org/abs/2205.13943) or [ConvMAE: Masked Convolution Meets Masked Autoencoders](https://arxiv.org/abs/2205.03892).
Such approaches could most likely be successfully integrated into CroCo but we are planning to work on that in the future.

Best
Philippe

**Comment by CaptainEven** [comment]
Thansk for the reply!
