### ISSUE TITLE
Question about .pth file setting

### ISSUE THREAD

**Issue by didot05** [naver/croco#13]
Hello, many thanks for your interesting paper. 

May I ask you about the settings under which these two checkpoint files: 
stereoflow_models/crocostereo_subtrain_vitb_smalldecoder.pth, stereoflow_models/crocostereo_subtrain_vitb_basedecoder.pth were trained? 
I'm curious about the number of epochs, the dataset used, and whether there was a separate pretraining .pth file used when creating above .pth files. 
Thank you.

**Comment by didot05** [comment]
thank you for your help!

**Comment by didot05** [comment]
Hello,

I have one little question about the measuring stage with the KITTI dataset.

I tried to measure the result of the experiment with the following command as you provided,

$python stereoflow/test.py --model stereoflow_models/crocostereo_finetune_kitti.pth --dataset "Kitti15('test')" --save submission --tile_overlap 0.9

and now I would like to measure the metric values of the result with the KITTI dataset. 

When I try to use the command: $python stereoflow/test.py --model stereoflow_models/crocostereo_finetune_kitti.pth --dataset "Kitti15('test')" --save metrics --tile_overlap 0.9

the error occurs with the following message:
assert gt.size(1)==1, gt.size()
AttributeError: 'NoneType' object has no attribute 'size'

May I ask you if there is some other way to measure the metric result?

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

Internal "Metrics" computed in this codebase cannot be on the test set as the ground-truth is private. This is why it is failing. You would need to upload the file created with the option `--save submission` to the official server in case you want the official metrics on the test set.

Best
Philippe

**Comment by didot05** [comment]
Thank you for your quick response!

I now comprehend the reason behind receiving the error log.

But I'm a bit confused about the procedure for uploading the file, as mentioned in your response with the "-save submission" option, to the official server. Could you please provide a more detailed explanation of the steps involved in measuring the metrics?

I appreciate your help.

**Comment by didot05** [comment]
thank you so much for your reply!!
