### ISSUE TITLE
The submission of MPI-sintel Dataset

### ISSUE THREAD

**Issue by buxiangzhiren** [naver/croco#16]
Hello,

I want to express my gratitude for sharing your code – it has been incredibly helpful.

I have a query regarding the submission process for the MPI-Sintel test dataset results. I attempted to register at http://sintel.is.tue.mpg.de/sessions, but encountered a technical issue. The website displayed the error message "ActiveRecord::StatementInvalid in UsersController#create SQLite3::SQLException: cannot rollback - no transaction is active: rollback transaction". This seems to prevent me from creating a new account.

Could you please advise on how to proceed with the submission, or if there's an alternative method available?

Thank you for your assistance and time.

**Comment by PhilippeWeinzaepfel** [comment]
Sorry but we cannot provide any support for problems related to the MPI-Sintel leaderboard.
