### ISSUE TITLE
Is there any bug in the pytorch RoPE codes?

### ISSUE THREAD

**Issue by ewrfcas** [naver/croco#3]
https://github.com/naver/croco/blob/2e72b41d2cb14165fbf28e7a9dbde5a316157fcf/models/pos_embed.py#L133

Following the original implementation of RoPE (https://github.com/ZhuiyiTechnology/roformer), this line should be
```
x1, x2 = x[..., ::2], x[..., 1::2]
return torch.cat((-x2, x1), dim=-1)
```

**Comment by jerome-revaud** [comment]
Hi @ewrfcas 

I'm not too sure which piece of code you're referring to. We based our implementation on the default implementation in FlashAttention's RoPE (`interleave = False`)
https://github.com/Dao-AILab/flash-attention/blob/a03f6f8e9ea6692568d98411b464034c22304afd/flash_attn/layers/rotary.py#L13-L19

Anyway, passing from interleaved to non-interleaved is easy (just a view + permute).

**Comment by ewrfcas** [comment]
Thanks for your reply. I will further check about the code in FlashAttention!
