### ISSUE TITLE
CrocoV2 performance on object recognition benchmarks.

### ISSUE THREAD

**Issue by truncs** [naver/croco#30]
Even though CrocoV2 wasn't trained on a object centric dataset I am curious whether there was some benchmarking done on Cars dataset (which might have some overlap) or if image segmentation was evaluated on CityScapes or equivalent.

 The paper does mention that for ADE20K 44.7 IoU was obtained. Was this a linear probe or multiple scales were used? It would be interesting to know whether the performance does increase if more data is used.

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

We had evaluating CroCo-Stereo and CroCo-Flow on datasets such as Kitti that contain urban environments and results were already pretty strong. Also, in [dust3r](https://dust3r.europe.naverlabs.com/), the model is finetuned including datasets like CO3D and state-of-the-art results are obtained on such object-centric datasets. So I would say that it is probably better to have such data in the pre-training stage, but having them in the fine-tuning stage might also be enough.

The ADE20K protocol is the same as [MultiMAE](https://github.com/EPFL-VILAB/MultiMAE/blob/main/FINETUNING.md#semantic-segmentation). I don't remember the exact protocol but from what I remember, this is not linear probe, this is single scale, and this is on a resized version of the dataset; to be double checked.

Best
Philippe

**Comment by truncs** [comment]
Got it! So can I conjecture based on this that Croco will perform competitively if there was enough multiview object centric data?

**Comment by PhilippeWeinzaepfel** [comment]
Yes
