### ISSUE TITLE
Availability of using my own images on CrocoFlow

### ISSUE THREAD

**Issue by Youngkwan-Cho** [naver/croco#8]
Thank you for your CrocoStereo and CrocoFlow codes.
I have read through the CrocoFlow codes to use my own image dates to see the results.
However, I am having difficulty doing so and thus is there any description or inference model available?
Thanks.

**Comment by PhilippeWeinzaepfel** [comment]
Have taken a look at the demo notebook for stereo/flow here : https://github.com/naver/croco/blob/master/croco-stereo-flow-demo.ipynb . You should have to replace the path to images and that is all.

**Comment by Youngkwan-Cho** [comment]
Thank you so much.
