### ISSUE TITLE
domain generalization of croco-stereo

### ISSUE THREAD

**Issue by jiaw-z** [naver/croco#9]
Helle, thanks for your shared code and checkpoints.
I am interested in the domain generalization ability of croco-stereo. I evaluate the pre-trained checkpoint "crocostereo.pth" on KITTI datasets
However, I got the D1 error rate of 14.00 on KITTI 2012  and 19.38 on KITTI 2015, which is worse than recent stereo networks.
Could you let me know if you have evaluated the generalization ability and whether I made an improper inference process?
I feel a little strange as the checkpoint is trained on large scale data and with popular data augmentation.

**Comment by PhilippeWeinzaepfel** [comment]
Hi,

We have not tried to evaluate any domain generalization. Architecture like CroCo-Stereo that directly regresses the disparity might not be the best for generalization compared to the ones based on explicit cost volumes, but they can be quickly finetuned.

**Comment by jiaw-z** [comment]
Thank you, 
I also appreciate the ability of croco after fine-tuning.
